Change clang test

diff --git a/.github/workflows/industrial_ci_action.yaml b/.github/workflows/industrial_ci_action.yaml
--- a/.github/workflows/industrial_ci_action.yaml
+++ b/.github/workflows/industrial_ci_action.yaml
@@ -22,24 +22,15 @@ jobs:
   
   clang_format_check:
     runs-on: ubuntu-latest
-    strategy:
-      matrix:
-        env:
-          - {OS_NAME: ubuntu, OS_CODE_NAME: focal, ROS_DISTRO: noetic, DOCKER_IMAGE: "samxl/scancontrol:sdk_v1.0.0"}
-  
+
     steps:
-    - name: Checkout repository
+    - name: Checkout Repository
       uses: actions/checkout@v2
 
-    - name: Run industrial_ci with Clang Format check
-      uses: ros-industrial/industrial_ci@master
-      env: ${{ matrix.env }}
-      with:
-        BUILD_TOOL: catkin
-        CATKIN_LINT: 'false'
-        CLANG_FORMAT_CHECK: "file"
-        CLANG_FORMAT_VERSION: "10"
-
-        # You might need to adjust the path if your package is not at the root of the repository
-        CATKIN_PKGS: "$(basename $GITHUB_REPOSITORY)"
-  
+    - name: Run Clang Format Check
+      run: |
+        find . -name "*.cpp" -o -name "*.hpp" | xargs clang-format-10 --output-replacements-xml | grep -c "<replacement "
+        if [ $? -eq 0 ]; then
+          echo "Clang Format check failed. Please run clang-format locally and commit the changes."
+          exit 1
+        fi
